language: node_js
nodejs:
    - "8"
script: yarn build
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "build"
  github_token: $GITHUB_TOKEN
  on:
    branch: master